[project]
name = "foundation-medicine-parser"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "polars>=1.21.0",
    "python-dateutil>=2.9.0.post0",
    "rich>=13.9.4",
    "xlsxwriter>=3.2.1",
]
